// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using RX.Nyss.Data;

namespace RX.Nyss.Data.Migrations
{
    [DbContext(typeof(NyssContext))]
    [Migration("20191008083856_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RX.Nyss.Data.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectHealthRiskId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectHealthRiskId");

                    b.ToTable("Alert");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.AlertRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlertRuleId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId");

                    b.ToTable("AlertRecipient");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.AlertRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountThreshold")
                        .HasColumnType("int");

                    b.Property<int?>("HoursThreshold")
                        .HasColumnType("int");

                    b.Property<int?>("MetersThreshold")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AlertRule");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.ApplicationLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("LanguageCode")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.ToTable("ApplicationLanguage");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.ContentLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("LanguageCode")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.ToTable("ContentLanguages");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.DataCollector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalPhoneNumber")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("DataCollectorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<int>("VillageId")
                        .HasColumnType("int");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("VillageId");

                    b.HasIndex("ZoneId");

                    b.ToTable("DataCollector");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("District");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.HealthRisk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AlertRuleId")
                        .HasColumnType("int");

                    b.Property<int>("HealthRiskCode")
                        .HasColumnType("int");

                    b.Property<string>("HealthRiskType")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId");

                    b.ToTable("HealthRisk");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.Localization", b =>
                {
                    b.Property<int>("ApplicationLanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ApplicationLanguageId", "Key");

                    b.ToTable("Localization");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.LocalizedTemplate", b =>
                {
                    b.Property<int>("ApplicationLanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.HasKey("ApplicationLanguageId", "Key");

                    b.ToTable("LocalizedTemplate");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.NationalSociety", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContentLanguageId")
                        .HasColumnType("int");

                    b.Property<string>("DistrictCustomName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("RegionCustomName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("VillageCustomName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ZoneCustomName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("ContentLanguageId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("NationalSocieties");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContentLanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("NationalSocietyId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TimeZone")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("ContentLanguageId");

                    b.HasIndex("NationalSocietyId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.ProjectHealthRisk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AlertRuleId")
                        .HasColumnType("int");

                    b.Property<string>("FeedbackMessage")
                        .HasColumnType("nvarchar(160)")
                        .HasMaxLength(160);

                    b.Property<int>("HealthRiskId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId");

                    b.HasIndex("HealthRiskId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectHealthRisk");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("NationalSocietyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NationalSocietyId");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataCollectorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsTraining")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("ProjectHealthRiskId")
                        .HasColumnType("int");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(160)")
                        .HasMaxLength(160);

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("DataCollectorId");

                    b.HasIndex("ProjectHealthRiskId");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalPhoneNumber")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("ApplicationLanguageId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Organization")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationLanguageId");

                    b.ToTable("User");

                    b.HasDiscriminator<string>("Role").HasValue("User");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.Village", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Village");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("VillageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VillageId");

                    b.ToTable("Zone");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.DataManagerUser", b =>
                {
                    b.HasBaseType("RX.Nyss.Data.Models.User");

                    b.Property<DateTime?>("ConsentedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasConsented")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDataOwner")
                        .HasColumnType("bit");

                    b.Property<int?>("NationalSocietyId")
                        .HasColumnType("int");

                    b.HasIndex("NationalSocietyId");

                    b.HasDiscriminator().HasValue("DataManager");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.SupervisorUser", b =>
                {
                    b.HasBaseType("RX.Nyss.Data.Models.User");

                    b.Property<int?>("DataManagerUserId")
                        .HasColumnType("int");

                    b.Property<int?>("NationalSocietyId")
                        .HasColumnName("SupervisorUser_NationalSocietyId")
                        .HasColumnType("int");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VillageId")
                        .HasColumnType("int");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasIndex("DataManagerUserId");

                    b.HasIndex("NationalSocietyId");

                    b.HasIndex("VillageId");

                    b.HasIndex("ZoneId");

                    b.HasDiscriminator().HasValue("Supervisor");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.Alert", b =>
                {
                    b.HasOne("RX.Nyss.Data.Models.ProjectHealthRisk", "ProjectHealthRisk")
                        .WithMany()
                        .HasForeignKey("ProjectHealthRiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.AlertRecipient", b =>
                {
                    b.HasOne("RX.Nyss.Data.Models.AlertRule", "AlertRule")
                        .WithMany()
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.DataCollector", b =>
                {
                    b.HasOne("RX.Nyss.Data.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RX.Nyss.Data.Models.SupervisorUser", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RX.Nyss.Data.Models.Village", "Village")
                        .WithMany()
                        .HasForeignKey("VillageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RX.Nyss.Data.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.District", b =>
                {
                    b.HasOne("RX.Nyss.Data.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.HealthRisk", b =>
                {
                    b.HasOne("RX.Nyss.Data.Models.AlertRule", "AlertRule")
                        .WithMany()
                        .HasForeignKey("AlertRuleId");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.Localization", b =>
                {
                    b.HasOne("RX.Nyss.Data.Models.ApplicationLanguage", "ApplicationLanguage")
                        .WithMany()
                        .HasForeignKey("ApplicationLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.LocalizedTemplate", b =>
                {
                    b.HasOne("RX.Nyss.Data.Models.ApplicationLanguage", "ApplicationLanguage")
                        .WithMany()
                        .HasForeignKey("ApplicationLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.NationalSociety", b =>
                {
                    b.HasOne("RX.Nyss.Data.Models.ContentLanguage", "ContentLanguage")
                        .WithMany()
                        .HasForeignKey("ContentLanguageId");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.Project", b =>
                {
                    b.HasOne("RX.Nyss.Data.Models.ContentLanguage", "ContentLanguage")
                        .WithMany()
                        .HasForeignKey("ContentLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RX.Nyss.Data.Models.NationalSociety", "NationalSociety")
                        .WithMany()
                        .HasForeignKey("NationalSocietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.ProjectHealthRisk", b =>
                {
                    b.HasOne("RX.Nyss.Data.Models.AlertRule", "AlertRule")
                        .WithMany()
                        .HasForeignKey("AlertRuleId");

                    b.HasOne("RX.Nyss.Data.Models.HealthRisk", "HealthRisk")
                        .WithMany()
                        .HasForeignKey("HealthRiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RX.Nyss.Data.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.Region", b =>
                {
                    b.HasOne("RX.Nyss.Data.Models.NationalSociety", "NationalSociety")
                        .WithMany()
                        .HasForeignKey("NationalSocietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.Report", b =>
                {
                    b.HasOne("RX.Nyss.Data.Models.DataCollector", "DataCollector")
                        .WithMany()
                        .HasForeignKey("DataCollectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RX.Nyss.Data.Models.ProjectHealthRisk", "ProjectHealthRisk")
                        .WithMany()
                        .HasForeignKey("ProjectHealthRiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("RX.Nyss.Data.Models.DataCollectionPointCase", "DataCollectionPointCase", b1 =>
                        {
                            b1.Property<int>("ReportId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int?>("DeathCount")
                                .HasColumnType("int");

                            b1.Property<int?>("FromOtherVillagesCount")
                                .HasColumnType("int");

                            b1.Property<int?>("ReferredCount")
                                .HasColumnType("int");

                            b1.HasKey("ReportId");

                            b1.ToTable("Report");

                            b1.WithOwner()
                                .HasForeignKey("ReportId");
                        });

                    b.OwnsOne("RX.Nyss.Data.Models.ReportCase", "KeptCase", b1 =>
                        {
                            b1.Property<int>("ReportId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int?>("CountFemalesAtLeastFive")
                                .HasColumnType("int");

                            b1.Property<int?>("CountFemalesBelowFive")
                                .HasColumnType("int");

                            b1.Property<int?>("CountMalesAtLeastFive")
                                .HasColumnType("int");

                            b1.Property<int?>("CountMalesBelowFive")
                                .HasColumnType("int");

                            b1.HasKey("ReportId");

                            b1.ToTable("Report");

                            b1.WithOwner()
                                .HasForeignKey("ReportId");
                        });

                    b.OwnsOne("RX.Nyss.Data.Models.ReportCase", "ReportedCase", b1 =>
                        {
                            b1.Property<int>("ReportId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int?>("CountFemalesAtLeastFive")
                                .HasColumnType("int");

                            b1.Property<int?>("CountFemalesBelowFive")
                                .HasColumnType("int");

                            b1.Property<int?>("CountMalesAtLeastFive")
                                .HasColumnType("int");

                            b1.Property<int?>("CountMalesBelowFive")
                                .HasColumnType("int");

                            b1.HasKey("ReportId");

                            b1.ToTable("Report");

                            b1.WithOwner()
                                .HasForeignKey("ReportId");
                        });
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.User", b =>
                {
                    b.HasOne("RX.Nyss.Data.Models.ApplicationLanguage", "ApplicationLanguage")
                        .WithMany()
                        .HasForeignKey("ApplicationLanguageId");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.Village", b =>
                {
                    b.HasOne("RX.Nyss.Data.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.Zone", b =>
                {
                    b.HasOne("RX.Nyss.Data.Models.Village", "Village")
                        .WithMany()
                        .HasForeignKey("VillageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.DataManagerUser", b =>
                {
                    b.HasOne("RX.Nyss.Data.Models.NationalSociety", "NationalSociety")
                        .WithMany()
                        .HasForeignKey("NationalSocietyId");
                });

            modelBuilder.Entity("RX.Nyss.Data.Models.SupervisorUser", b =>
                {
                    b.HasOne("RX.Nyss.Data.Models.DataManagerUser", "DataManagerUser")
                        .WithMany()
                        .HasForeignKey("DataManagerUserId");

                    b.HasOne("RX.Nyss.Data.Models.NationalSociety", "NationalSociety")
                        .WithMany()
                        .HasForeignKey("NationalSocietyId");

                    b.HasOne("RX.Nyss.Data.Models.Village", "Village")
                        .WithMany()
                        .HasForeignKey("VillageId");

                    b.HasOne("RX.Nyss.Data.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId");
                });
#pragma warning restore 612, 618
        }
    }
}
