using Microsoft.EntityFrameworkCore.Migrations;

namespace RX.Nyss.Data.Migrations
{
    public partial class AddCountrySeedData : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "Countries",
                columns: new[] { "Id", "CountryCode", "Name" },
                values: new object[,]
                {
                    { 1, "AX", "Åland Islands" },
                    { 154, "AN", "Netherlands Antilles" },
                    { 155, "NC", "New Caledonia" },
                    { 156, "NZ", "New Zealand" },
                    { 157, "NI", "Nicaragua" },
                    { 158, "NE", "Niger" },
                    { 159, "NG", "Nigeria" },
                    { 160, "NU", "Niue" },
                    { 161, "NF", "Norfolk Island" },
                    { 162, "MP", "Northern Mariana Islands" },
                    { 163, "NO", "Norway" },
                    { 164, "OM", "Oman" },
                    { 165, "PK", "Pakistan" },
                    { 153, "NL", "Netherlands" },
                    { 166, "PW", "Palau" },
                    { 168, "PA", "Panama" },
                    { 169, "PG", "Papua New Guinea" },
                    { 170, "PY", "Paraguay" },
                    { 171, "PE", "Peru" },
                    { 172, "PH", "Philippines" },
                    { 173, "PN", "Pitcairn" },
                    { 174, "PL", "Poland" },
                    { 175, "PT", "Portugal" },
                    { 176, "PR", "Puerto Rico" },
                    { 177, "QA", "Qatar" },
                    { 178, "RE", "Reunion" },
                    { 179, "RO", "Romania" },
                    { 167, "PS", "Palestinian Territory, Occupied" },
                    { 180, "RU", "Russian Federation" },
                    { 152, "NP", "Nepal" },
                    { 150, "NA", "Namibia" },
                    { 124, "LY", "Libyan Arab Jamahiriya" },
                    { 125, "LI", "Liechtenstein" },
                    { 126, "LT", "Lithuania" },
                    { 127, "LU", "Luxembourg" },
                    { 128, "MO", "Macao" },
                    { 129, "MK", "Macedonia, The Former Yugoslav Republic of" },
                    { 130, "MG", "Madagascar" },
                    { 131, "MW", "Malawi" },
                    { 132, "MY", "Malaysia" },
                    { 133, "MV", "Maldives" },
                    { 134, "ML", "Mali" },
                    { 135, "MT", "Malta" },
                    { 151, "NR", "Nauru" },
                    { 136, "MH", "Marshall Islands" },
                    { 138, "MR", "Mauritania" },
                    { 139, "MU", "Mauritius" },
                    { 140, "YT", "Mayotte" },
                    { 141, "MX", "Mexico" },
                    { 142, "FM", "Micronesia, Federated States of" },
                    { 143, "MD", "Moldova, Republic of" },
                    { 144, "MC", "Monaco" },
                    { 145, "MN", "Mongolia" },
                    { 146, "MS", "Montserrat" },
                    { 147, "MA", "Morocco" },
                    { 148, "MZ", "Mozambique" },
                    { 149, "MM", "Myanmar" },
                    { 137, "MQ", "Martinique" },
                    { 181, "RW", "RWANDA" },
                    { 182, "SH", "Saint Helena" },
                    { 183, "KN", "Saint Kitts and Nevis" },
                    { 215, "TL", "Timor-Leste" },
                    { 216, "TG", "Togo" },
                    { 217, "TK", "Tokelau" },
                    { 218, "TO", "Tonga" },
                    { 219, "TT", "Trinidad and Tobago" },
                    { 220, "TN", "Tunisia" },
                    { 221, "TR", "Turkey" },
                    { 222, "TM", "Turkmenistan" },
                    { 223, "TC", "Turks and Caicos Islands" },
                    { 224, "TV", "Tuvalu" },
                    { 225, "UG", "Uganda" },
                    { 226, "UA", "Ukraine" },
                    { 214, "TH", "Thailand" },
                    { 227, "AE", "United Arab Emirates" },
                    { 229, "US", "United States" },
                    { 230, "UM", "United States Minor Outlying Islands" },
                    { 231, "UY", "Uruguay" },
                    { 232, "UZ", "Uzbekistan" },
                    { 233, "VU", "Vanuatu" },
                    { 234, "VE", "Venezuela" },
                    { 235, "VN", "Viet Nam" },
                    { 236, "VG", "Virgin Islands, British" },
                    { 237, "VI", "Virgin Islands, U.S." },
                    { 238, "WF", "Wallis and Futuna" },
                    { 239, "EH", "Western Sahara" },
                    { 240, "YE", "Yemen" },
                    { 228, "GB", "United Kingdom" },
                    { 213, "TZ", "Tanzania, United Republic of" },
                    { 212, "TJ", "Tajikistan" },
                    { 211, "TW", "Taiwan, Province of China" },
                    { 184, "LC", "Saint Lucia" },
                    { 185, "PM", "Saint Pierre and Miquelon" },
                    { 186, "VC", "Saint Vincent and the Grenadines" },
                    { 187, "WS", "Samoa" },
                    { 188, "SM", "San Marino" },
                    { 189, "ST", "Sao Tome and Principe" },
                    { 190, "SA", "Saudi Arabia" },
                    { 191, "SN", "Senegal" },
                    { 192, "CS", "Serbia and Montenegro" },
                    { 193, "SC", "Seychelles" },
                    { 194, "SL", "Sierra Leone" },
                    { 195, "SG", "Singapore" },
                    { 196, "SK", "Slovakia" },
                    { 197, "SI", "Slovenia" },
                    { 198, "SB", "Solomon Islands" },
                    { 199, "SO", "Somalia" },
                    { 200, "ZA", "South Africa" },
                    { 201, "GS", "South Georgia and the South Sandwich Islands" },
                    { 202, "ES", "Spain" },
                    { 203, "LK", "Sri Lanka" },
                    { 204, "SD", "Sudan" },
                    { 205, "SR", "Suriname" },
                    { 206, "SJ", "Svalbard and Jan Mayen" },
                    { 207, "SZ", "Swaziland" },
                    { 208, "SE", "Sweden" },
                    { 209, "CH", "Switzerland" },
                    { 210, "SY", "Syrian Arab Republic" },
                    { 123, "LR", "Liberia" },
                    { 122, "LS", "Lesotho" },
                    { 121, "LB", "Lebanon" },
                    { 120, "LV", "Latvia" },
                    { 33, "BG", "Bulgaria" },
                    { 34, "BF", "Burkina Faso" },
                    { 35, "BI", "Burundi" },
                    { 36, "KH", "Cambodia" },
                    { 37, "CM", "Cameroon" },
                    { 38, "CA", "Canada" },
                    { 39, "CV", "Cape Verde" },
                    { 40, "KY", "Cayman Islands" },
                    { 41, "CF", "Central African Republic" },
                    { 42, "TD", "Chad" },
                    { 43, "CL", "Chile" },
                    { 44, "CN", "China" },
                    { 32, "BN", "Brunei Darussalam" },
                    { 45, "CX", "Christmas Island" },
                    { 47, "CO", "Colombia" },
                    { 48, "KM", "Comoros" },
                    { 49, "CG", "Congo" },
                    { 50, "CD", "Congo, The Democratic Republic of the" },
                    { 51, "CK", "Cook Islands" },
                    { 52, "CR", "Costa Rica" },
                    { 53, "CI", "Cote D\"Ivoire" },
                    { 54, "HR", "Croatia" },
                    { 55, "CU", "Cuba" },
                    { 56, "CY", "Cyprus" },
                    { 57, "CZ", "Czech Republic" },
                    { 58, "DK", "Denmark" },
                    { 46, "CC", "Cocos (Keeling) Islands" },
                    { 31, "IO", "British Indian Ocean Territory" },
                    { 30, "BR", "Brazil" },
                    { 29, "BV", "Bouvet Island" },
                    { 2, "AL", "Albania" },
                    { 3, "DZ", "Algeria" },
                    { 4, "AS", "American Samoa" },
                    { 5, "AD", "AndorrA" },
                    { 6, "AO", "Angola" },
                    { 7, "AI", "Anguilla" },
                    { 8, "AQ", "Antarctica" },
                    { 9, "AG", "Antigua and Barbuda" },
                    { 10, "AR", "Argentina" },
                    { 11, "AM", "Armenia" },
                    { 12, "AW", "Aruba" },
                    { 13, "AU", "Australia" },
                    { 14, "AT", "Austria" },
                    { 15, "AZ", "Azerbaijan" },
                    { 16, "BS", "Bahamas" },
                    { 17, "BH", "Bahrain" },
                    { 18, "BD", "Bangladesh" },
                    { 19, "BB", "Barbados" },
                    { 20, "BY", "Belarus" },
                    { 21, "BE", "Belgium" },
                    { 22, "BZ", "Belize" },
                    { 23, "BJ", "Benin" },
                    { 24, "BM", "Bermuda" },
                    { 25, "BT", "Bhutan" },
                    { 26, "BO", "Bolivia" },
                    { 27, "BA", "Bosnia and Herzegovina" },
                    { 28, "BW", "Botswana" },
                    { 59, "DJ", "Djibouti" },
                    { 241, "ZM", "Zambia" },
                    { 60, "DM", "Dominica" },
                    { 62, "EC", "Ecuador" },
                    { 94, "HM", "Heard Island and Mcdonald Islands" },
                    { 95, "VA", "Holy See (Vatican City State)" },
                    { 96, "HN", "Honduras" },
                    { 97, "HK", "Hong Kong" },
                    { 98, "HU", "Hungary" },
                    { 99, "IS", "Iceland" },
                    { 100, "IN", "India" },
                    { 101, "ID", "Indonesia" },
                    { 102, "IR", "Iran, Islamic Republic Of" },
                    { 103, "IQ", "Iraq" },
                    { 104, "IE", "Ireland" },
                    { 105, "IM", "Isle of Man" },
                    { 93, "HT", "Haiti" },
                    { 106, "IL", "Israel" },
                    { 108, "JM", "Jamaica" },
                    { 109, "JP", "Japan" },
                    { 110, "JE", "Jersey" },
                    { 111, "JO", "Jordan" },
                    { 112, "KZ", "Kazakhstan" },
                    { 113, "KE", "Kenya" },
                    { 114, "KI", "Kiribati" },
                    { 115, "KP", "Korea, Democratic People\"S Republic of" },
                    { 116, "KR", "Korea, Republic of" },
                    { 117, "KW", "Kuwait" },
                    { 118, "KG", "Kyrgyzstan" },
                    { 119, "LA", "Lao People\"S Democratic Republic" },
                    { 107, "IT", "Italy" },
                    { 92, "GY", "Guyana" },
                    { 91, "GW", "Guinea-Bissau" },
                    { 90, "GN", "Guinea" },
                    { 63, "EG", "Egypt" },
                    { 64, "SV", "El Salvador" },
                    { 65, "GQ", "Equatorial Guinea" },
                    { 66, "ER", "Eritrea" },
                    { 67, "EE", "Estonia" },
                    { 68, "ET", "Ethiopia" },
                    { 69, "FK", "Falkland Islands (Malvinas)" },
                    { 70, "FO", "Faroe Islands" },
                    { 71, "FJ", "Fiji" },
                    { 72, "FI", "Finland" },
                    { 73, "FR", "France" },
                    { 74, "GF", "French Guiana" },
                    { 75, "PF", "French Polynesia" },
                    { 76, "TF", "French Southern Territories" },
                    { 77, "GA", "Gabon" },
                    { 78, "GM", "Gambia" },
                    { 79, "GE", "Georgia" },
                    { 80, "DE", "Germany" },
                    { 81, "GH", "Ghana" },
                    { 82, "GI", "Gibraltar" },
                    { 83, "GR", "Greece" },
                    { 84, "GL", "Greenland" },
                    { 85, "GD", "Grenada" },
                    { 86, "GP", "Guadeloupe" },
                    { 87, "GU", "Guam" },
                    { 88, "GT", "Guatemala" },
                    { 89, "GG", "Guernsey" },
                    { 61, "DO", "Dominican Republic" },
                    { 242, "ZW", "Zimbabwe" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Countries");
        }
    }
}
