namespace RX.Nyss.Web.Features.Common
{
    public enum Policy
    {
        NationalSocietyAccess,
        SmsGatewayAccess,
        ProjectAccess,
        ManagerAccess,
        DataConsumerAccess,
        TechnicalAdvisorAccess,
        SupervisorAccess,
        DataCollectorAccess,
        MultipleDataCollectorsAccess,
        HeadManagerAccess,
        RegionWriteAccess,
        RegionAccess,
        DistrictWriteAccess,
        DistrictAccess,
        VillageWriteAccess,
        VillageAccess,
        ZoneWriteAccess,
        ZoneAccess,
        AlertAccess,
        ReportAccess,
        CoordinatorAccess,
        OrganizationAccess,
        ProjectOrganizationAccess,
        AlertRecipientAccess
    }
}
